routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(
    ['prefix'=>'admin', 'as' => 'admin.', 'middleware'=>['auth','role:admin|member']],
function () {
    Route::get('/', 'AdminController@index');
    Route::resource('kategori', 'KategoriController');
    Route::resource('tag', 'TagController');
    Route::resource('artikel', 'ArtikelController');
    Route::post('artikel/{publish}', 'ArtikelController@Publish')->name('artikel.publish');
}
);

// frontend
Route::get('blog', 'FrontendController@blog');
Route::get('about', 'FrontendController@about');
Route::get('service', 'FrontendController@service');
Route::get('product', 'FrontendController@product');
Route::get('contact', 'FrontendController@contact');
Route::get('blog/{artikel}', 'FrontendController@singleblog');
Route::get('blog/kategori/{kategori}', 'FrontendController@artikelkategori');
Route::get('blog/tag/{tag}', 'FrontendController@artikeltag');

// cekson
Route::get('instagram', 'FrontendController@cekinsta');

// Api
Route::resource('/kontak', 'KontakController');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['nama', 'slug'];
    public $timestamps = true;

    public function Artikel()
    {
        return $this->belongsToMany('App\Artikel');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use Alert;
use Validator;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::latest()->paginate(12);
        return view('admin.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:255|unique:tags'
        ];

        $message = [
            'name.required' => 'The name Tag is required',
            'name.unique' => 'Tag is already used find another tag',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $tags = new Tag;
        $tags->name = $request->name;
        $tags->slug = str_slug($request->name, '-');
        $tags->save();
        Alert::success('Data successfully saved', 'Good Job')->autoclose(1000);
        return redirect()->route('admin.tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|max:255'
        ];

        $message = [
            'name.required' => 'The name tag is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $tags = Tag::findOrFail($id);
        $tags->name = $request->name;
        $tags->slug = str_slug($request->name, '-');
        $tags->save();
        Alert::success('Data successfully edited', 'Good Job')->autoclose(1000);
        return redirect()->route('admin.tag.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::findOrFail($id)->delete();
        Alert::success('Data successfully deleted', 'Good Job')->autoclose(1000);
        return back();
    }
}

resources/views/admin/tag/create.blade.php
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalTitle2">Tambah tag</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="zmdi zmdi-close"></span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('admin.tag.store') }}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>tag</label>
                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Masukan tag" required>
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-outline" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/tag/edit.blade.php
<div class="modal fade tag{{ $data->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalTitle2">Tambah tag</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="zmdi zmdi-close"></span>
                </button>
            </div>
            <div class="modal-body">
                 <form action="{{ route('admin.tag.update',$data->id) }}" method="post">
                    <input name="_method" type="hidden" value="PATCH">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>tag</label>
                            <input type="text" value="{{ $data->name }}" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Masukan tag" required>
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-outline" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/tag/index.blade.php
@extends('layouts.admin')
@section('css')

@endsection
@section('js')
<script src="{{asset('/assets/js/components/datatables-init.js')}}"></script>
@endsection
@section('header')
<nav class="breadcrumb-wrapper" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url('/admin')}}"><i class="icon dripicons-home"></i></a></li>
        <li class="breadcrumb-item"><a href="javascript:void(0)">tag</a></li>
    </ol>
</nav>
@endsection
@section('content')
<div class="col-12">
        <center>
            <button type="button" class="btn btn-primary btn-rounded btn-floating btn-outline" data-toggle="modal" data-target=".bd-example-modal-lg">
                Tambah Data
            </button>
        </center><br><br>
        @include('admin.tag.create')
    <div class="card">
        <h5 class="card-header">
        tag
        </h5>
        <div class="card-body">
            <table id="bs4-table" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>tag</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                @php $no =1; @endphp
                @foreach($tags as $data)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$data->name}}</td>
                    <td>
                        <form method="post" action="{{ route('admin.tag.destroy',$data->id) }}" class="form">
                        {{-- <a href="{{ route('admin.tag.edit',$data->id) }}" class="btn btn-warning btn-outline">Edit</a> --}}
                        <button type="button" class="btn btn-warning btn-rounded btn-outline" data-toggle="modal" data-target=".tag{{ $data->id }}">
                            Edit
                        </button>
                        		<input name="_token" type="hidden" value="{{ csrf_token() }}">
								<input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-danger btn-rounded btn-floating btn-outline js-submit-confirm">Delete</button>
                        </form>
                    </td>
                </tr>
                @include('admin.tag.edit')
                @endforeach

                </tbody>

            </table>


        </div>
    </div>
</div>
@push('scripts')
@endpush
@endsection

resources/views/admin/tag/show.blade.php
{{ $artikel->Kategori->nama_kategori }} <br>
{{ $artikel->User->name }} <br>
{{ $artikel->judul }} <br>
{!! $artikel->konten !!}