routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(
    ['prefix'=>'admin', 'as' => 'admin.', 'middleware'=>['auth','role:admin|member']],
function () {
    Route::get('/', 'AdminController@index');
    Route::resource('kategori', 'KategoriController');
    Route::resource('tag', 'TagController');
    Route::resource('artikel', 'ArtikelController');
    Route::post('artikel/{publish}', 'ArtikelController@Publish')->name('artikel.publish');
}
);

// frontend
Route::get('blog', 'FrontendController@blog');
Route::get('about', 'FrontendController@about');
Route::get('service', 'FrontendController@service');
Route::get('product', 'FrontendController@product');
Route::get('contact', 'FrontendController@contact');
Route::get('blog/{artikel}', 'FrontendController@singleblog');
Route::get('blog/kategori/{kategori}', 'FrontendController@artikelkategori');
Route::get('blog/tag/{tag}', 'FrontendController@artikeltag');

// cekson
Route::get('instagram', 'FrontendController@cekinsta');

// Api
Route::resource('/kontak', 'KontakController');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Session;

class Kategori extends Model
{
    protected $fillable = ['nama_kategori','slug'];
    public $timestamps = true;

    public function Artikel()
    {
        return $this->hasMany('App\Artikel', 'kategori_id');
    }

    public static function boot()
    {
        parent::boot();
        self::deleting(function ($kategori) {
            // mengecek apakah penulis masih punya buku
            if ($kategori->Artikel->count() > 0) {
                // menyiapkan pesan error
                $html = 'Kategori tidak bisa dihapus karena masih digunakan oleh Artikel : ';
                $html .= '<ul>';
                foreach ($kategori->Artikel as $data) {
                    $html .= "<li>$data->judul</li>";
                }
                $html .= '</ul>';
                Session::flash("flash_notification", [
                "level"=>"danger",
                "message"=>$html
                ]);
                // membatalkan proses penghapusan
                return false;
            }
        });
    }
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Kategori;
use Illuminate\Http\Request;
use Alert;
use Validator;
class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::all();
        // dd($kategori);
        return view('admin.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'nama_kategori' => 'required|unique:kategoris',
        ];

        $message = [
            'nama_kategori.required' => 'The Category is required',
            'nama_kategori.unique' => 'Your Category can not be same',
        ];
        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails())
        {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }

        // $request->validate([
        //     'nama_kategori' => 'required|unique:kategoris',
        // ]);

        $kategori = new kategori;
        $kategori->nama_kategori = $request->nama_kategori;
        $kategori->slug = str_slug($request->nama_kategori, '-');
        // dd($kategori);
        $kategori->save();
        Alert::success('Data successfully saved','Good Job')->autoclose(1500);
        return redirect()->route('admin.kategori.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function show(Kategori $kategori)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function edit(Kategori $kategori)
    {
        return view('admin.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kategori $kategori)
    {
        $request->validate([
            'nama_kategori' => 'required',
        ]);
        $a = kategori::findOrFail($kategori->id);
        ;
        $a->nama_kategori = $request->nama_kategori;
        // dd($kategori);
        $a->save();
        Alert::success('Data successfully edited','Good Job')->autoclose(1000);
        return redirect()->route('admin.kategori.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function destroy(kategori $kategori)
    {
        if(!Kategori::destroy($kategori->id)){
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return redirect()->back();
        } else{
            Alert::success('Data successfully deleted', 'Good Job')->autoclose(1000);
            return redirect()->route('admin.kategori.index');
        }
    }
}

resources/views/admin/kategori/create.blade.php
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalTitle2">Tambah Kategori</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="zmdi zmdi-close"></span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('admin.kategori.store') }}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Kategori</label>
                            <input type="text" name="nama_kategori" class="form-control{{ $errors->has('nama_kategori') ? ' is-invalid' : '' }}" placeholder="Masukan Kategori" required>
                            @if ($errors->has('nama_kategori'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('nama_kategori') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-outline" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/kategori/edit.blade.php
<div class="modal fade kategori{{ $data->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalTitle2">Tambah Kategori</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="zmdi zmdi-close"></span>
                </button>
            </div>
            <div class="modal-body">
                 <form action="{{ route('admin.kategori.update',$data->id) }}" method="post">
                    <input name="_method" type="hidden" value="PATCH">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Kategori</label>
                            <input type="text" value="{{ $data->nama_kategori }}" name="nama_kategori" class="form-control{{ $errors->has('nama_kategori') ? ' is-invalid' : '' }}" placeholder="Masukan Kategori" required>
                            @if ($errors->has('nama_kategori'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('nama_kategori') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-outline" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/kategori/index.blade.php
@extends('layouts.admin')
@section('css')

@endsection
@section('js')
<script src="{{asset('/assets/js/components/datatables-init.js')}}"></script>
@endsection
@section('header')
<nav class="breadcrumb-wrapper" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url('/admin')}}"><i class="icon dripicons-home"></i></a></li>
        <li class="breadcrumb-item"><a href="javascript:void(0)">Kategori</a></li>
    </ol>
</nav>
@endsection
@section('content')
<div class="col-12">
        <center>
            <button type="button" class="btn btn-primary btn-rounded btn-floating btn-outline" data-toggle="modal" data-target=".bd-example-modal-lg">
                Tambah Data
            </button>
        </center><br><br>
        @include('admin.kategori.create')
    <div class="card">
        <h5 class="card-header">
        Kategori
        </h5>
        <div class="card-body">
            <table id="bs4-table" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Kategori</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                @php $no =1; @endphp
                @foreach($kategori as $data)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$data->nama_kategori}}</td>
                    <td>
                        <form method="post" action="{{ route('admin.kategori.destroy',$data->id) }}" class="form">
                        {{-- <a href="{{ route('admin.kategori.edit',$data->id) }}" class="btn btn-warning btn-outline">Edit</a> --}}
                        <button type="button" class="btn btn-warning btn-rounded btn-outline" data-toggle="modal" data-target=".kategori{{ $data->id }}">
                            Edit
                        </button>
                        		<input name="_token" type="hidden" value="{{ csrf_token() }}">
								<input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-danger btn-rounded btn-floating btn-outline js-submit-confirm">Delete</button>
                        </form>
                    </td>
                </tr>
                @include('admin.kategori.edit')
                @endforeach

                </tbody>

            </table>


        </div>
    </div>
</div>
@push('scripts')
@endpush
@endsection

resources/views/admin/kategori/show.blade.php
{{ $artikel->Kategori->nama_kategori }} <br>
{{ $artikel->User->name }} <br>
{{ $artikel->judul }} <br>
{!! $artikel->konten !!}